### ISSUE TITLE
Can specific border radius??

### ISSUE THREAD

**Issue by kenchoong** [adorableio/avatars-api#62] opened 2017-08-25 03:42 UTC
Can I specific the border radius in the URL of the api??

**Comment by rylnd** [comment] 2017-08-25 14:33
Hi @kenchoong! This was discussed previously in #38, but we currently do not support border-radius as part of the avatars API.

If you've got CSS available to style, we'd suggest doing that for now. However, if you don't, and since you're not the first one to make this request, we'll look into how feasible this would be to do. As always, Pull Requests welcome and encouraged :)

**Comment by rylnd** [comment] 2017-08-28 22:13
Closing as a duplicate of #38

**Closed by rylnd** 2017-08-28 22:13 UTC
